<div style="text-align:left;font-size:2em"><span style="font-weight:bolder;font-size:1.25em">SP2273 | Learning Portfolio</span><br><br><span style="font-weight:bold;color:darkred">Storing Data (Good) Exercises</span></div>

#### Exercise 1

Subsetting: *subsettting means to select a subset of data in a list or array*

Indexing: Accessing a specific element in a list or array using the index position of the element in that list or array. The index position is determined by its position in the sequence of elements. It can be accessed by counting the position of the element from the front or from the back of the sequence (reverse indexing). 
*Indexing refers to selecting one element*

Slicing: *slicing refers to selecting a range of elements*

Masking: Masking means to hide or cover up "False" data in a True/False (list) or array. 
*Masking only works with NumPy arrays, not Python lists*

#### Exercise 2

In [1]:
import numpy as np
np_array_2d = np.array([[1, "A"], [3, "C"], [2, "B"], [4, "D"],
                        [5, "E"], [7, "G"], [6, "F"], [8, "H"],
                        [10, "J"], [9, "I"]])
long_np_array = np_array_2d[:]
print(np_array_2d)

[['1' 'A']
 ['3' 'C']
 ['2' 'B']
 ['4' 'D']
 ['5' 'E']
 ['7' 'G']
 ['6' 'F']
 ['8' 'H']
 ['10' 'J']
 ['9' 'I']]


In [ ]:
numbers_np_array = long_np_array[:,0] 
# first position in bracket indicates the index/ elements to be selected
# one number at the first position refers to the index of one element to be selected
# placing a ":" at that position means "all" 
# placing a number after a ":" indicates the number of elements to be selected, counting from the front
print(numbers_np_array)

['1' '3' '2' '4' '5' '7' '6' '8' '10' '9']


In [26]:
# Converting list into numbers/integers (coz it is in string now)
int_np_array = numbers_np_array.astype(int)
print(numbers_np_array[4], type(int_np_array[4])) #checking code type

5 <class 'numpy.int64'>


In [ ]:
remainder_np_array = int_np_array%2
int_np_array%2

array([1, 1, 0, 0, 1, 1, 0, 0, 0, 1])

In [31]:
mask_even = remainder_np_array != 0 # those with remainder = 1 are odd

In [ ]:
numbers_np_array[mask_even] 
# first array is the original array, within [] the array is a True/False

array(['1', '3', '5', '7', '9'], dtype='<U21')

#### Exercise 3

In [24]:
numbers_matrix = [
    [66, 50, 57, -1, -1],
    [92, -1, 88, -1, -1],
    [75, -1, -1, 76, -1],
    [-1, 51, 87, -1, -1],
    [71, -1, 67, -1, 69]
    ]
numbers_matrix_np = np.array(numbers_matrix)
print(numbers_matrix_np[0,0], type(numbers_matrix_np[0,0]))

66 <class 'numpy.int64'>


In [17]:
x=[1,2]
x[0]=3
print(x)

[3, 2]


In [22]:
x=(1,2)
x.append(3)
# x[0]=3
print(x)

AttributeError: 'tuple' object has no attribute 'append'

In [26]:
less_than_50 = numbers_matrix_np < 50
# masking step: identifying & isolating all elements < 50 in array
print(less_than_50)
print(len(numbers_matrix_np[less_than_50]))

numbers_matrix_np[less_than_50]=-1
# above step allows conversion of isolated elements into another value
# outer array: "where"; which list/array
# box bracketed array: "who"/ which elements to mask/isolate
# = "what" to change the selected/isolated elements into

print(numbers_matrix_np) # the originial array has been changed.

[[False False False  True  True]
 [False  True False  True  True]
 [False  True  True False  True]
 [ True False False  True  True]
 [False  True False  True False]]
13
[[66 50 57 -1 -1]
 [92 -1 88 -1 -1]
 [75 -1 -1 76 -1]
 [-1 51 87 -1 -1]
 [71 -1 67 -1 69]]


In [27]:
above_50 = numbers_matrix_np > 50
# masking step
numbers_matrix_np[above_50] = 1
print (numbers_matrix_np)

[[ 1 50  1 -1 -1]
 [ 1 -1  1 -1 -1]
 [ 1 -1 -1  1 -1]
 [-1  1  1 -1 -1]
 [ 1 -1  1 -1  1]]


In [ ]:
equals_50 = numbers_matrix_np == 50
# masking step 
# note that masking is always asking a question/ setting a condition 
# for identifying the elements to be isolated
print(equals_50)
numbers_matrix_np[equals_50] = 0

[[False  True False False False]
 [False False False False False]
 [False False False False False]
 [False False False False False]
 [False False False False False]]


In [32]:
print(numbers_matrix_np)

[[ 1  0  1 -1 -1]
 [ 1 -1  1 -1 -1]
 [ 1 -1 -1  1 -1]
 [-1  1  1 -1 -1]
 [ 1 -1  1 -1  1]]
