<div style="text-align:left;font-size:2em"><span style="font-weight:bolder;font-size:1.25em">SP2273 | Learning Portfolio</span><br><br><span style="font-weight:bold;color:darkred">Storing Data (Need) Exercises</span></div>

### Exercise 1

Question 1
1. Both lists and arrays store data/ elements
2. Elements or data in lists and arrays can be accessed through  methods such as indexing

Quesion 2
1. Arrays are fundamentally designed to be used for quick maths whereas Lists are used more for data storage.
2. Arrays can only store data in one generalised format, eg. string code, whereas Lists can store data in multiple formats.

Question 3
1. A dictionary is a large store of data that uses keys and their corresponding linked information, where they are separated by ":". It allows for easy access of information from a single storage.

### Exercise 2 (Indexing)

In [2]:
py_list = ["a1", "b2", "c3", "d4", "e5", "f6", "g7", "h8", "i9", "j10"]
print(py_list[0])    # Prints 'a1'
print(py_list[2])    # Prints 'c3'
print(py_list[4])   # Prints 'e5'
print(py_list[6])    # Prints 'g7'
print(py_list[8])   # Prints 'i9'

a1
c3
e5
g7
i9


In [ ]:
#### Exercise 3 ("Index again")

### Exercise 3

In [3]:
elements = ['Hydrogen',
            'Helium', 'Lithium',
            'Beryllium', 'Boron', 'Carbon',
            'Nitrogen', 'Oxygen',
            'Fluorine',
            'Neon']

In [4]:
print(elements[4])

Boron


In [5]:
print(elements[-4])

Nitrogen


### Exercise 4 (How many ones)

In [3]:
numbers=[45, 60, 1, 30, 96, 1, 96, 57, 16, 1,
        99, 62, 86, 43, 42, 60, 59, 1, 1, 35,
        83, 47, 34, 28, 68, 23, 22, 92, 1, 79,
        1, 29, 94, 72, 46, 47, 1, 74, 32, 20,
        8, 37, 35, 1, 89, 29, 86, 19, 43, 61]                  

In [4]:
import numpy as np
np_numbers = np.array(numbers)

In [ ]:
sum(np_numbers==1)
# note: why cant I use 'len(np_numbers==1)' ?

np.int64(9)

Hence the number of ones in this list/array is 9

### Exercise 5 (A Matter of Statistics)

In [21]:
x_1 = [1, 4, 9, 16, 25, 36, 49, 64, 81, 100]
x_2 = [1, 8, 27, 64, 125, 216, 343, 512, 729, 1000]

In [24]:
np_x_1 = np.array(x_1)
np_x_2 = np.array(x_2)

#### Question 1 (Mean)

Mean of X1

In [6]:
np_x_1.mean()

np.float64(38.5)

Mean of X2

In [7]:
np_x_2.mean()

np.float64(302.5)

#### Question 2 (Standard Deviation)

SD of X1

In [29]:
np_x_1.std()

np.float64(32.41990129534635)

SD of X2

In [30]:
np_x_2.std()

np.float64(326.0893282522444)

#### Question 3 (Pearson Correlation Coefficient)

In [ ]:
x1 = [1, 4, 9, 16, 25, 36, 49, 64, 81, 100]
x2 = [1, 8, 27, 64, 125, 216, 343, 512, 729, 1000]

np_x_1 = np.array(x_1)
np_x_2 = np.array(x_2)

In [ ]:
x1_minus_miu = np_x_1 - np_x_1.mean()


In [32]:
x1_minus_miu = np_x_1 - np_x_1.mean()
# use .sum() as an attribute of the array.. will sum(x1_minus_miu) work?
# can also use np.sum()
x2_minus_miu = np_x_2 - np_x_2.mean()

numerator = sum(x1_minus_miu*x2_minus_miu)

print(x1_minus_miu)
print(sum_x2_minus_miu)
print(numerator)

[-37.5 -34.5 -29.5 -22.5 -13.5  -2.5  10.5  25.5  42.5  61.5]
0.0
104362.5


In [33]:
x1_sumsquares = np.sum((x1_minus_miu)**2)
x2_sumsquares = np.sum((x2_minus_miu)**2)
denominator = np.sqrt(x1_sumsquares*x2_sumsquares)

In [34]:
r = numerator/denominator
print(r)

0.9871796626270701


#### Question 4

In [ ]:
r = np.corrcoef(np_x_1, np_x_2)
print(r)
# produces a matrix showing the correlation coefficient between the 
# 1st list and itself, followed by the 1st list's corrcoef with the 2nd list

[[1.         0.98717966]
 [0.98717966 1.        ]]


Comparing my results with np.corrcoef,
1. the value of r between the 2 data sets produced in my results was much longer compared to using np.corrcoef

2. The results produced are in a matrix format, where the first and second columns respresents comparison with x1 and x2 respectively, and the top and bottom rows represent comparison with x1 and x2 respectively, to produce 4 values of r.

In [ ]:
## dictionary: {[np_x_1], [np_x_2]}
# can i use smth like this to make them into one data set?
### no, make a 2D array instead: 
data_matrix = np.array([[0, 5],
                       [1, 6],
                       [2, 7],
                       [3, 8],
                       [4, 9]])
np.corrcoef(data_matrix)

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])