<div style="text-align:left;font-size:2em"><span style="font-weight:bolder;font-size:1.25em">SP2273 | Learning Portfolio</span><br><br><span style="font-weight:bold;color:darkred">Storing Data (Good)</span></div>

# What to expect in this chapter

# 1 Subsetting: Indexing and Slicing

## 1.1 Lists & Arrays in 1D | Subsetting & Indexing

In [1]:
import numpy as np

In [3]:
py_list = ['a1', 'b2', 'c3', 'd4', 'e5',
           'f6', 'g7', 'h8', 'i9', 'j10']
np_array = np.array(py_list)

# Pick one
x = py_list # OR
x = np_array

In [4]:
py_list[1:6:2] # python lists start from 0, so '1' refers to the second object in the list
# py_list [first index (inclusive) : last index (exclusive) : steps/ intervals of index choosing] 

['b2', 'd4', 'f6']

In [7]:
np_array = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10]) 
np_array > 3

array([False, False, False,  True,  True,  True,  True,  True,  True,
        True])

In [ ]:
mask = np_array > 3
mask # asking for mask data


array([False, False, False,  True,  True,  True,  True,  True,  True,
        True])

In [13]:
np_array[mask]

array([ 4,  5,  6,  7,  8,  9, 10])

## 1.2 Arrays only | Subsetting by masking

## 1.3 Lists & Arrays in 2D | Indexing & Slicing

## 1.4 Growing lists

# Some loose ends

## 1.5 Tuples

## 1.6 Be VERY careful when copying

## Footnotes