<div style="text-align:left;font-size:2em"><span style="font-weight:bolder;font-size:1.25em">SP2273 | Learning Portfolio</span><br><br><span style="font-weight:bold;color:darkred">Storing Data (Need)</span></div>

# What to expect in this chapter

# 1 Lists, Arrays & Dictionaries

## 1.1 Let’s compare

#### Python Lists

In [8]:
# start with a list name that is not "list" (in blue)
py_super_names = ["black widow", "iron man", "spiderman"]
py_real_names = ["Natasha Romanoff", "Tony Stark", "Peter Parker"]

#### Numpy Arrays

In [ ]:
### Notes
# (stored very differently from python lists)
# 1. Only likes to store one type of data (eg. strings vs numbers), so it will convert all data into one form.
# 2. If you convert a Python list that consists of numbers and words 
# into a Numpy array, the array will convert all data 
# into the most general form; words.
# Numpy arrays must be in a fixed "shape" (needs consistent shape);
# because numpy is built for very fast maths calculations.
# NumPy Array elements are always enclosed by ([]) 
# where () is for the NumPy function, and [] for the list of data inside

In [42]:
import numpy as np
# () brackets are used for functions, [] are then used to enclose lists
np_super_names = np.array(["black widow", "iron man", "spiderman"]) 
np_real_names = np.array(["Natasha Romanoff", "Tony Stark", "Peter Parker"])

In [ ]:
# Converting list into array
np_array = np.array(py_real_names)
# Use the "np.array()" function and place the list to be converted inside

## 1.2 Accessing data from a list (or array)

In [ ]:
py_super_names[0]
# An index is the numerical position of an element in a data storage
# Python is a "zero-indexed" language; indexes in lists are numbered
# starting from 0.
# Using a [] allows you to access information/ data in a list.

'black widow'

In [14]:
py_super_names[2]

'spiderman'

In [ ]:
py_super_names[-1]
# using negative indexes allows us to count from the back of the list
# In this 3-item list, both "-1" and "2" refer to the list's last item  

'spiderman'

In [ ]:
# the same can be applied to accessing data from arrays


#### Dictionary

In [ ]:
superhero_info = { # dictionaries use curly brackets!
    "Natasha Romanoff": "black widow", #note the use of commas, indents and colons
    "Tony Stark": "iron man",
    "Peter Parker": "spiderman"
 }

## 1.3 Accessing data from a dictionary

In [5]:
superhero_info["Natasha Romanoff"] 
# doing this will print the linked info to the bracketed string of text

'black widow'

- Dictionaries use a key and an associated value separated by a colon 
    - In the above scenario, "Natasha Romanoff" is the key and "black widow" is its associated text.
- For lists and arrays, each set of strings (superhero names & real names) must be in the same position in order for it to be used like a dictionary.

## 1.4 Higher dimensional lists

In [ ]:
# How to have linked data without making 2 separate lists or arrays?
py_superhero_info = [['Natasha Romanoff', 'Black Widow'],
                     ['Tony Stark', 'Iron Man'],
                     ['Stephen Strange', 'Doctor Strange']]
# Can I say that there are technically 3 lists in this one list since
# there are 3 groups of data enclosed in [] ?

# 2 Lists vs. Arrays

In [18]:
# Preparing your lists and arrays
py_list_numbers = [1, 2, 3, 4, 5]
np_numbers = np.array(py_list_numbers) # converts python list into an np array

Lists

Arrays

In [13]:
mask = np_numbers > 3
np_numbers[mask]

array([4, 5])

## 2.1 Size

In [21]:
py_list_2d = [[1, "A"], [2, "B"], [3, "C"], [4, "D"],
              [5, "E"], [6, "F"], [7, "G"], [8, "H"],
              [9, "I"], [10, "J"]]

np_array_2d = np.array(py_list_2d)      # Reusing the Python list 
                                        # to create a NEW
                                        # NumPy array

In [24]:
# use len() function to calculate the number of elements in a list/array
len(py_list_2d)

10

In [ ]:
np_array_2d.shape
# '.' indicates ownership. In this case, shape is not a function.
# Instead, it is a property or attribute of the numpy array above.
# "shape" shows the number of columns & rows of elements in a list/array

(10, 2)

## 2.2 Arrays are fussy about type

- Arrays can only contain elements/ data in the same format.

- If you convert a Python list with containing both floats/integers (numbers) and strings into an NumPy array, the resultant array will convert the element formats into the most generalised form; all elements will be strings.


## 2.3 Adding a number

In [19]:
py_list_numbers + [100] # to add a value into a python list

[1, 2, 3, 4, 5, 100]

## 2.4 Adding another list

In [31]:
# Let 
py_list_1 = [2, 4, 6, 8, 10]
py_list_2 = [3, 6, 9, 12, 15]

In [ ]:
# To make a new list that is a combination of the 2 above:
py_list_1 + py_list_2 # note that the order of the lists matters.

[2, 4, 6, 8, 10, 3, 6, 9, 12, 15]

## 2.5 Multiplying by a Number

In [ ]:
# For Python Lists
py_list_2*2 # doubles/ duplicates the set of data in the same order

[3, 6, 9, 12, 15, 3, 6, 9, 12, 15]

In [ ]:
# For NumPy Arrays
np_numbers*2 # each element in the data set is doubled/ multipled

array([ 2,  4,  6,  8, 10])

## 2.6 Squaring

In [ ]:
# Python Lists cannot be squared
# NumPy Arrays can be squared
np_numbers**2 # Each element in the array will be squared

array([ 1,  4,  9, 16, 25])

## 2.7 Asking questions

In [ ]:
# Below, asking Python kernel which elements are equals to 3 in the array
np_numbers == 3

array([False, False,  True, False, False])

In [ ]:
py_list_numbers = [1, 2, 3, 4, 5]
py_list_numbers == 3 ## does not work the way it does for arrays

False

In [ ]:
py_element = [3]
py_element == 3 # still does not work

False

## 2.8 Mathematics

**Mathematic Functions**

sum(py_list)     # sum() is a base Python function

max(py_list)     # max() is a base Python function

min(py_list)     # min() is a base Python function

np_array.sum()

np_array.max()

np_array.min()

np_array.mean()

np_array.std()

In [15]:
print(py_list_numbers)

[1, 2, 3, 4, 5]


In [17]:
# Calculating Mean using Python Lists
sum(py_list_numbers)/len(py_list_numbers)

3.0

In [ ]:
# Calculating Mean using np arrays
np_numbers.mean() # mean is an intrinsic method of this array
# or
np.mean(np_numbers) # mean is a function defined inside np package

np.float64(3.0)

In [19]:
# Calculating standard deviation (np)
np_numbers.std()

np.float64(1.4142135623730951)

## Footnotes